default: &default
  adapter: postgresql
  encoding: unicode
  # docker-compose.yml のサービス名 'db' を指定
  host: <%= ENV.fetch("DB_HOST") { "db" } %>
  username: <%= ENV.fetch("POSTGRES_USER") { "postgres" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "password" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: satto_ai_development